---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: seerr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: API_KEY
      remoteRef:
        key: SEER_API_KEY
