---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &name bitwarden-tls-certs
spec:
  secretName: *name
  dnsNames:
    - bitwarden-sdk-server.kube-system.svc.servonet.lan
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: step
    kind: ClusterIssuer
