---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: radarr
  values:
    controllers:
      main:
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1001
            fsGroup: 1001
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 5.20.1.9773@sha256:8187c129a78fdfe15b1603db9175abd2be0e1ca2e99ea3733987c3ae941da165
            env:
              TZ: "America/Detroit"
              PUID: 1000
              PGID: 1001
              RADARR__INSTANCE_NAME: Radarr
              RADARR__PORT: &port 7878
            resources:
              requests:
                memory: 250Mi
                cpu: 20m
              limits:
                memory: 1500Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: *port
    route:
      main:
        hostnames:
          - radarr.servonet.lan
        parentRefs:
          - name: envoy-internal
            namespace: networking
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: "ceph-block"
        size: 1Gi
        accessMode: ReadWriteOnce
        retain: true
      downloads:
        existingClaim: nas-downloads
      movies:
        existingClaim: nas-movies
