---
clusterName: servonet
endpoint: https://10.4.3.1:6443
domain: servonet.lan

talosVersion: v1.7.5
kubernetesVersion: v1.30.2

allowSchedulingOnControlPlanes: true

nodes:
  - hostname: tom-364c
    nameservers:
      - 10.4.1.1
    ipAddress: "10.4.3.32"
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: true
        addresses:
          - 10.4.3.32
        routes:
          - network: 0.0.0.0/0 # The route's network (destination).
            gateway: 10.4.1.1 # The route's gateway (if empty, creates link scope route).
            metric: 1024 # The optional metric for the route.
        vip:
          ip: "10.4.3.1"
  - hostname: tom-3a11
    ipAddress: "10.4.3.33"
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: true
        addresses:
          - 10.4.3.33
        routes:
          - network: 0.0.0.0/0 # The route's network (destination).
            gateway: 10.4.1.1 # The route's gateway (if empty, creates link scope route).
            metric: 1024 # The optional metric for the route.
        vip:
          ip: "10.4.3.1"
  - hostname: tom-3e67
    ipAddress: "10.4.3.34"
    controlPlane: true
    installDisk: /dev/mmcblk0
    networkInterfaces:
      - interface: eth0
        dhcp: true
        addresses:
          - 10.4.3.34
        routes:
          - network: 0.0.0.0/0 # The route's network (destination).
            gateway: 10.4.1.1 # The route's gateway (if empty, creates link scope route).
            metric: 1024 # The optional metric for the route.
        vip:
          ip: "10.4.3.1"
