---
- name: Add user to sudoers
  ansible.builtin.copy:
    content: "tom ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/tom_nopasswd"
    mode: "0440"

- name: Add additional user SSH public keys
  ansible.posix.authorized_key:
    user: "tom"
    key: "{{ item }}"
  loop: "{{ ssh_authorized_keys }}"
  when:
    - ssh_authorized_keys is defined
    - ssh_authorized_keys is iterable
    - ssh_authorized_keys | length > 0
