---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/node-feature-discovery/charts
      chart: node-feature-discovery
      version: 0.16.3
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    nodeFeatureRule:
      createCRD: true
    worker:
      config:
        core:
          labelSources:
            - cpu
            - custom
            - pci
            - usb
        sources:
          usb:
            deviceClassWhitelist:
              - "02"
              - "03"
              - "0e"
              - "ef"
              - "fe"
              - "ff"
            deviceLabelFields:
              - class
              - vendor
              - device
          custom:
            - name: intel-gpu
              matchOn:
                - pciId:
                    class: ["0300"]
                    vendor: ["8086"]
            - name: dvb-tuner
              matchOn:
                - usbId:
                    class: ["ff"]
                    vendor: ["2040"]
                    device: ["826d"]
