---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: sabnzbd
  values:
    controllers:
      main:
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1001
            fsGroup: 1001

        containers:
          main:
            image:
              repository: ghcr.io/home-operations/sabnzbd
              tag: 4.5.5@sha256:da57e01cdebc547852b6df85c8df8c0e4d87792742c7608c5590dc653b184e8c
            env:
              SABNZBD__PORT: &port 8080
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.servonet.lan,
                sabnzbd.media.svc.servonet.lan,
                sabnzbd.media.svc.cluster.local
            resources:
              requests:
                cpu: 5m
                memory: "250Mi"
              limits:
                memory: "4500Mi"

    service:
      main:
        controller: main
        ports:
          http:
            port: *port
    route:
      main:
        hostnames:
          - sabnzbd.servonet.lan
        parentRefs:
          - name: envoy-internal
            namespace: networking

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: "ceph-block"
        size: 1Gi
        accessMode: ReadWriteOnce
        retain: true
      downloads:
        existingClaim: nas-downloads
