---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        type: statefulset
        pod:
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            fsGroup: 1001

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/sabnzbd
              tag: 4.2.3@sha256:fa8ddea45e56b0e36454c3c0eb30ff5521d90aeb5b35301656ae9236680be3a9
            env:
              SABNZBD__PORT: &port 8080
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.lan,
                sabnzbd.media.svc.servonet.lan
            resources:
              requests:
                cpu: 1
                memory: "250Mi"
              limits:
                memory: "1500Mi"

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "step"
        hosts:
          - host: &host "sabnzbd.lan"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: "sabnzbd-cert"

    persistence:
      config:
        enabled: true
        type: custom
        volumeSpec:
          resources:
            requests:
              storage: 1Mi
          volumeMode: Filesystem
          accessModes:
            - ReadWriteMany
          nfs:
            server: "gpc"
            path: /pool/storage-0/media/config/sabnzbd
        mountPath: /config
      media:
        existingClaim: nas-media
