---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        type: statefulset
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1001
            fsGroup: 1001

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/sabnzbd
              tag: 4.4.1@sha256:36674664a94760ae934c09b1d97546a3e79a0f110edda88085e74778c26d68e3
            env:
              SABNZBD__PORT: &port 8080
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.lan,
                sabnzbd.media.svc.cluster.local
            resources:
              requests:
                cpu: 5m
                memory: "250Mi"
              limits:
                memory: "4500Mi"

    service:
      main:
        controller: main
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "step"
        hosts:
          - host: &host "sabnzbd.lan"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: "sabnzbd-cert"

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: "ceph-block"
        size: 1Gi
        accessMode: ReadWriteOnce
        retain: true
      downloads:
        existingClaim: nas-downloads
