---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: qbittorrent
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/qbittorrent-libtorrentv1
              tag: 5.2.0@sha256:da73e0b5b48ee64aefeaf30d07debbb4f619bfa8eea1ed775f5932acc6c7fb7a
            env:
              TZ: "America/Detroit"
              QBT_WEBUI_PORT: &port 80
              QBT_TORRENTING_PORT: &torrentPort 31288
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                memory: 250Mi
                cpu: 20m
              limits:
                memory: 1500Mi
    defaultPodOptions:
      terminationGracePeriodSeconds: 300
      securityContext:
        runAsNonRoot: true
        runAsUser: 3000
        runAsGroup: 3001
        fsGroup: 3001
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        forceRename: "{{ .Release.Name }}"
        primary: true
        controller: main
        ports:
          http:
            port: *port
      bittorrent:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.42.104
        externalTrafficPolicy: Local
        ports:
          bittorrent-tcp:
            port: *torrentPort
            protocol: TCP
    route:
      main:
        hostnames:
          - "{{ .Release.Name }}.servonet.lan"
        parentRefs:
          - name: envoy-internal
            namespace: networking
        rules:
          - backendRefs:
              - identifier: main
                port: *port
    persistence:
      tmp:
        type: emptyDir
      config:
        existingClaim: qbittorrent
      downloads:
        existingClaim: nas-downloads
      movies:
        existingClaim: nas-movies
      tv:
        existingClaim: nas-tv
      archive:
        existingClaim: nas-archive
