version: 2
updates:
  - directory: .github/
    package-ecosystem: github-actions
    schedule:
      timezone: "05:42 UTC"
      interval: weekly
      day: sunday
  - directory: provision/terraform
    package-ecosystem: terraform
    schedule:
      interval: weekly
      time: "04:31"
      day: monday
