version: '3.9'
services:
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        volumes:
            - /mnt/media/config/sonarr:/config
            - /mnt/media/tv:/tv
            - /mnt/media/downloads:/downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 8989:8989
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/Detroit
        restart: always

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        volumes:
            - /mnt/media/config/radarr:/config
            - /mnt/media/movies:/movies
            - /mnt/media/downloads:/downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 7878:7878
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/Detroit
        restart: always


    nzbget:
        image: linuxserver/nzbget
        container_name: nzbget
        volumes:
            - /mnt/media/config/nzbget:/config
            - /mnt/media/downloads/completed:/complete
            - /mnt/media/downloads:/downloads
        ports:
            - 6789:6789
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/Detroit
        restart: always
