---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: step-issuer
spec:
  interval: 4h
  chart:
    spec:
      chart: step-issuer
      version: 1.9.8
      sourceRef:
        kind: HelmRepository
        name: smallstep-charts
        namespace: flux-system
  values:
    servieAccount:
      create: true
    certManager:
      serviceAccount:
        name: cert-manager
        namespace: kube-system
