---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app freshrss
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  dependsOn:
    - name: rook-cluster
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  postBuild:
    substitute:
      APP: *app
  path: ./cluster/apps/selfhosted/freshrss/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: network
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
