---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: home-assistant
  namespace: home
spec:
  postgresVersion: 15
  dataSource:
    pgbackrest:
      repo:
        name: home-assistant
        volume:
          volumeClaimSpec:
            accessModes:
              - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
            storageClassName: postgres-nas-backup
            volumeName: postgres-nas-backup

  instances:
    - name: home-assistant
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteMany"
        resources:
          requests:
            storage: 1Gi
  users:
    - name: home-assistant
      databases:
        - home-assistant
      options: "SUPERUSER"
  backups:
    pgbackrest:
      repos:
        - name: home-assistant
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 1Gi
              storageClassName: postgres-nas-backup
              volumeName: postgres-nas-backup
