---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: home-assistant-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SECRET_TRUSTED_PROXIES_1: 10.42.0.0\16

        SECRET_HOME_LATITUDE: "{{ .hass_home_latitude }}"
        SECRET_HOME_LONGITUDE: "{{ .hass_home_longitude }}"

  dataFrom:
    - extract:
        key: home-assistant
      rewrite:
        - regexp:
            source: "(.*)"
            target: "hass_$1"
