---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        type: statefulset
        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 1Gi
              storageClass: "local-path"
              globalMounts:
                - path: /config

        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2025.10.4@sha256:449140e073d8d7814098cd62dfdbb326ad043f51a3c4d4721889369f46751d52
            # envFrom:
            #   - secretRef:
            #       name: home-assistant-secrets
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 500m
                memory: 1024M
              limits:
                memory: 2048M

    service:
      main:
        annotations:
          io.cilium/lb-ipam-ips: "${HASS_ADDRESS}"
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8123

    ingress:
      main:
        enabled: true
        className: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "step"
        hosts:
          - host: &host "hass.lan"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: "hass-cert"
