---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.13.10
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
  values:
    configInline:
      peers:
        - peer-address: ${BGP_ROUTER_ADDR}
          peer-asn: ${BGP_ROUTER_ASN}
          my-asn: ${METALLB_BGP_ASN}
      address-pools:
        - name: default
          protocol: bgp
          addresses:
            - "${METALLB_BGP_RANGE}"
          avoid-buggy-ips: true
    # prometheus:
    #   podMonitor:
    #     enabled: true
    #   prometheusRule:
    #     enabled: true
    speaker:
      frr:
        enabled: true
        image:
          repository: quay.io/frrouting/frr
          tag: 8.4.2
        metricsPort: 7473
      tolerations:
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"
