---
- name: stat oh-my-zsh
  stat:
    path: ~/.oh-my-zsh
  register: stat_omz_result

- name: install oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh
    dest: ~/Source/ohmyzsh
  when: not stat_omz_result.stat.exists

- name: run install script
  ansible.builtin.script: ~/Source/ohmyzsh/tools/install.sh
  when: not stat_omz_result.stat.exists

- name: create new ~/.zshrc
  template:
    src: files/.zshrc.j2
    dest: ~/.zshrc
  when: not stat_omz_result.stat.exists

- name: set dock and hot corners
  shell: defaults write com.apple.dock {{ item.key }} -{{ item.type }} {{ item.value }}
  loop: "{{ dock }}"

- name: restart dock
  shell: killall Dock

- name: vscode extensions
  shell: code --install-extension {{ item }}
  loop: "{{ vscode }}"

- name: stat id_ecdsa
  stat:
    path: ~/.ssh/id_ecdsa
  register: id_ecdsa

- name: generate ssh key
  shell: ssh-keygen -t ecdsa -b 521 -f ~/.ssh/id_ecdsa
  when: not id_ecdsa.stat.exists
