kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "nzbget.fullname" .}}
  labels:
    {{- include "nzbget.labels" . | nindent 4 }}
data:
  PUID: {{ .Values.puid | quote }}
  PGID: {{ .Values.pgid | quote }}
  TZ: {{ .Values.timezone | quote }}