---
services:
  qemu_kernel:
    image: ghcr.io/siderolabs/imager:${TALOS_VERSION}
    command:
      - iso
      - --arch
      - amd64
      - --system-extension-image
      - ghcr.io/siderolabs/intel-ucode:20240910@sha256:998f2d9c8e810605094dccfe89259a3b6de86264d6e91a3613417ca10d7e61ab
      - --system-extension-image
      - ghcr.io/siderolabs/qemu-guest-agent:9.1.0@sha256:cd8154036a0711f6f0a2ec9d6ce8539219d0e46a78e0eca22598d4d884f3f52c
      - --output-kind
      - kernel
    platform: linux/arm64
    privileged: true
    volumes:
      - "$PWD/assets/talos/${TALOS_VERSION}/qemu:/out:rw"
      - "/dev:/dev:rw"
  qemu:
    image: ghcr.io/siderolabs/imager:${TALOS_VERSION}
    command:
      - iso
      - --arch
      - amd64
      - --system-extension-image
      - ghcr.io/siderolabs/intel-ucode:20240910@sha256:998f2d9c8e810605094dccfe89259a3b6de86264d6e91a3613417ca10d7e61ab
      - --system-extension-image
      - ghcr.io/siderolabs/qemu-guest-agent:9.1.0@sha256:cd8154036a0711f6f0a2ec9d6ce8539219d0e46a78e0eca22598d4d884f3f52c
      - --output-kind
      - initramfs
    platform: linux/arm64
    privileged: true
    volumes:
      - "$PWD/assets/talos/${TALOS_VERSION}/qemu:/out:rw"
      - "/dev:/dev:rw"
  qemu_gpu_kernel:
    image: ghcr.io/siderolabs/imager:${TALOS_VERSION}
    command:
      - iso
      - --arch
      - amd64
      - --system-extension-image
      - ghcr.io/siderolabs/intel-ucode:20240910@sha256:998f2d9c8e810605094dccfe89259a3b6de86264d6e91a3613417ca10d7e61ab
      - --system-extension-image
      - ghcr.io/siderolabs/qemu-guest-agent:9.1.0@sha256:cd8154036a0711f6f0a2ec9d6ce8539219d0e46a78e0eca22598d4d884f3f52c
      - --system-extension-image
      - ghcr.io/siderolabs/nvidia-container-toolkit-lts:535.183.06-v1.16.1@sha256:f5239612224d47ea081836c67abc3a609a3c9b3d984b47c901fd65c56494976f
      - --system-extension-image
      - ghcr.io/siderolabs/nonfree-kmod-nvidia-lts:535.183.06-v1.8.1@sha256:23c3458bf1570d66a5e93236a22a5a1a7107ae9ce3e48b9e45b2cbfd41088857
      - --output-kind
      - kernel
    platform: linux/arm64
    privileged: true
    volumes:
      - "$PWD/assets/talos/${TALOS_VERSION}/qemu_gpu:/out:rw"
      - "/dev:/dev:rw"
  qemu_gpu:
    image: ghcr.io/siderolabs/imager:${TALOS_VERSION}
    command:
      - iso
      - --arch
      - amd64
      - --system-extension-image
      - ghcr.io/siderolabs/intel-ucode:20240910@sha256:998f2d9c8e810605094dccfe89259a3b6de86264d6e91a3613417ca10d7e61ab
      - --system-extension-image
      - ghcr.io/siderolabs/qemu-guest-agent:9.1.0@sha256:cd8154036a0711f6f0a2ec9d6ce8539219d0e46a78e0eca22598d4d884f3f52c
      - --system-extension-image
      - ghcr.io/siderolabs/nvidia-container-toolkit-lts:535.183.06-v1.16.1@sha256:f5239612224d47ea081836c67abc3a609a3c9b3d984b47c901fd65c56494976f
      - --system-extension-image
      - ghcr.io/siderolabs/nonfree-kmod-nvidia-lts:535.183.06-v1.8.1@sha256:23c3458bf1570d66a5e93236a22a5a1a7107ae9ce3e48b9e45b2cbfd41088857
      - --output-kind
      - initramfs
    platform: linux/arm64
    privileged: true
    volumes:
      - "$PWD/assets/talos/${TALOS_VERSION}/qemu_gpu:/out:rw"
      - "/dev:/dev:rw"
  intel_kernel:
    image: ghcr.io/siderolabs/imager:${TALOS_VERSION}
    command:
      - iso
      - --arch
      - amd64
      - --output-kind
      - kernel
    platform: linux/arm64
    privileged: true
    volumes:
      - "$PWD/assets/talos/${TALOS_VERSION}/intel:/out:rw"
      - "/dev:/dev:rw"
  intel:
    image: ghcr.io/siderolabs/imager:${TALOS_VERSION}
    command:
      - iso
      - --arch
      - amd64
      - --system-extension-image
      - ghcr.io/siderolabs/intel-ucode:20240910@sha256:998f2d9c8e810605094dccfe89259a3b6de86264d6e91a3613417ca10d7e61ab
      - --system-extension-image
      - ghcr.io/siderolabs/i915-ucode:20240909@sha256:58387e3dfb505602c7bd939bee0f546e6bc6b81f8131eb2d5c59858fd3cd61da
      - --output-kind
      - initramfs
    platform: linux/arm64
    privileged: true
    volumes:
      - "$PWD/assets/talos/${TALOS_VERSION}/intel:/out:rw"
      - "/dev:/dev:rw"
  rpi-kernel:
    image: ghcr.io/siderolabs/imager:${TALOS_VERSION}
    command:
      - iso
      - --arch
      - arm64
      - --overlay-image
      - ghcr.io/siderolabs/sbc-raspberrypi:v0.1.0-beta.2@sha256:900bfd99ae1ed13e8fc1ba2d130c80d3c4730370fbc0f2c8330dab91471991bc
      - --overlay-name
      - rpi_generic
      - --output-kind
      - kernel
    platform: linux/arm64
    privileged: true
    volumes:
      - "$PWD/assets/talos/${TALOS_VERSION}/rpi:/out:rw"
      - "/dev:/dev:rw"
  rpi:
    image: ghcr.io/siderolabs/imager:${TALOS_VERSION}
    command:
      - iso
      - --arch
      - arm64
      - --overlay-image
      - ghcr.io/siderolabs/sbc-raspberrypi:v0.1.0-beta.2@sha256:900bfd99ae1ed13e8fc1ba2d130c80d3c4730370fbc0f2c8330dab91471991bc
      - --overlay-name
      - rpi_generic
      - --output-kind
      - initramfs
    platform: linux/arm64
    privileged: true
    volumes:
      - "$PWD/assets/talos/${TALOS_VERSION}/rpi:/out:rw"
      - "/dev:/dev:rw"
