# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    ACME_EMAIL: ENC[AES256_GCM,data:XV8zTvACmbWw/+KQlaPB3F/l3TGSTYuW5FM=,iv:JA/uv/3IAa8JZn/vSdTq6OVemy66xqjF6Fn7ndm+WdM=,tag:sKiy33M3Pm3FX7y5TYX6/Q==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:6ixcJ1VDNUTxGJgUy7Gj,iv:bxNa6g5ZwBMQ9iR/Rx5WYaZuPigXxSbtb4Kpp0TiPzo=,tag:1WaxY3sXjT/R+Miqjn+tEw==,type:str]
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:YKgDeAeKkoCkqIn3TbohJfVTixAx/EViZpSx4z7e9be5VSI5rEjtZg==,iv:q+Gi4hslJsuTzJn9Ornj3lQR6i7005iifxQHF2K8K3U=,tag:jYnijSV1MvtMFX1aw0ThBA==,type:str]
sops:
    age:
        - recipient: age10tgyjaw5a7smf72m44k5g725wnyt9zt2crhq8ta5zcsc79n9jvasmxn2kx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRVliSnN1TEtpZnppNTB1
            NHI2KzdmY3ZaUlkyRlBNK1NMd3hFSmk2S3lvClV1eHBucmJpcTE5NzBFTmNFd3pJ
            NG9QS0xYSmhDQWYvNGdUWGwwM2tyd28KLS0tIHljU1pBWWw0RUd4MHE5ZzM4L0Rn
            N3o5d041UE93NzYyeEc4cWhNVHFmUm8Ko6qVgpLHSdSZ9W2VQ7nVgnQGnXdoJkMi
            yGAI6MGqsWkL2W4GcLcAPZo5aBmDsONon19DVb1fOrnqu2n0CBoNDw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age120w7753mv7dkmg78uu9lsjlplxprpy4kfgr8rx9vfkdckmtttees75m003
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaEFuNXNVVUtsS2VWa3pL
            TlNlaWcrSlZKY2I0TzVtSnk3V0xaRzJKR1YwClFiRnN3amU4djFabWFlQmF2cTRH
            bmN6ZnJkR3FvbVZCb0JtYm1aS3RxNEkKLS0tIFFnWWVYUUR0RjZ0NHY3WktMVkF6
            aUFjYW9JclB5aG9SNjZpMFVqb2VXNXcKVhfXbvJ0a6H53I4ZcioIkT6sl/LCHe43
            /AoSs6rJGrohu8lh9VT3hLfd3LwnMJ0qBv4NVhEz+5ENLVoFl0gbSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T22:11:50Z"
    mac: ENC[AES256_GCM,data:ZNq3TKn/Fdw0OWU1WftyZjp5MbWp3P+2nEIXUsF0WrfnDs7EkYU07YB794l7k58v1Z04VFFcP0lPsXsWRFG7GeiaJM5mv+LCRCfooikkNzFnPIaY1xNY3st3msnm/57AuRY+AgH3VlfvqCK8Sdgprmy01KB1lqF+tuEaM6r2bKY=,iv:ABC5VPKKkvFCKbIkPRTKk9HAFtzDGG/kOT4Cwi7Km94=,tag:w0xZ1+Wl81OO3evMMQaUEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
