---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lldap
  namespace: auth-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: lldap-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: LLDAP_JWT_SECRET
      remoteRef:
        key: LLDAP_JWT_SECRET
    - secretKey: LLDAP_LDAP_USER_PASS
      remoteRef:
        key: LLDAP_LDAP_USER_PASS
    - secretKey: LLDAP_USER_DN
      remoteRef:
        key: LLDAP_USER_DN
    - secretKey: LLDAP_LDAP_USER_EMAIL
      remoteRef:
        key: LLDAP_LDAP_USER_EMAIL
    - secretKey: LLDAP_KEY_SEED
      remoteRef:
        key: LLDAP_KEY_SEED
