---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app lldap
  namespace: flux-system
spec:
  targetNamespace: auth-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 10m
  path: "./cluster/apps/auth-system/lldap/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: network
  wait: true
  dependsOn:
    - name: rook-cluster
