---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: litellm-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: LITELLM_MASTER_KEY
    - secretKey: LITELLM_MACBOOK_OMLX_API_KEY
      remoteRef:
        key: LITELLM_MACBOOK_OMLX_API_KEY
    - secretKey: LITELLM_ORCAROUTER_API_KEY
      remoteRef:
        key: LITELLM_ORCAROUTER_API_KEY
