---
# install applications

- name: homebrew applications
  homebrew:
    state: latest
    name: "{{ item }}"
  loop: "{{ applications }}"

- name: homebrew cask applications
  homebrew_cask:
    state: present
    name: "{{ item }}"
  loop: "{{ casks }}"

- name: install npm packages
  npm:
    state: latest
    name: "{{ item }}"
  loop: "{{ npm-packages }}"

- name: install pip packages
  pip:
    name: "{{ item }}"
  loop: "{{ pip-packages }}"