---
# install applications

- name: homebrew applications
  homebrew:
    state: latest
    name: "{{ item }}"
  loop: "{{ applications }}"

- name: homebrew cask applications
  homebrew_cask:
    state: present
    name: "{{ item }}"
  loop: "{{ casks }}"

- name: install npm packages
  npm:
    state: latest
    name: "{{ item }}"
    global: yes
  loop: "{{ npm }}"

- name: pip test
  pip:
    name: "{{ pip }}"


- name: install gems
  gem:
    name: "{{ item }}"
  loop: "{{ gems }}"