---
- name: stat oh-my-zsh
  stat:
    path: ~/.oh-my-zsh
  register: stat_omz_result

- name: install oh-my-zsh
  git:
    repo: https://github.com/lambchop4prez/ohmyzsh
    dest: ~/.oh-my-zsh
  when: not stat_omz_result.stat.exists

- name: create new ~/.zshrc
  template:
    src: files/.zshrc.j2
    dest: ~/.zshrc