---
# Setup environment

# - name: setup dotfiles

# - name: set environment variables

# - name: install vscode extensions

- name: install oh-my-zsh
  shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/lambchop4prez/oh-my-zsh/master/tools/install.sh)"'
  args:
    creates: 