---
- hosts: gpc
  become: false
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pause for 3 seconds...
      pause:
        seconds: 3
  roles:
    - hypervisor.proxmox
    - storage.nas
    - storage.fusionio
