---
- hosts:
    - servonet
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var:  hostvars[inventory_hostname]
    - name: Pause for 3 seconds...
      pause:
        seconds: 3
  tasks:
    - name: Check if cluster is installed
      ansible.builtin.stat:
        path: "/etc/rancher/k3s/config.yaml"
      register: k3s_check_installed
      check_mode: false

    - name: Set manifest facts
      ansible.builtin.set_fact:
        k3s_server_manifests_templates: []
        k3s_server_manifests_urls: []
      when: k3s_check_installed.stat.exists

  roles:
    - role: common.ubuntu
      tags: ["common.ubuntu"]
    - role: ubuntu.k3s
      tags: ["ubuntu.k3s"]
