- hosts: local
  become: true
  gather_facts: true

  pre_tasks:
    - name: Pausing for 3 seconds...
      pause:
        seconds: 3
  
  roles:
    - role: workstation.macos
      tags: ['workstation']
  