- hosts: local
  become: true
  gather_facts: true

  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5
  
  roles:
    - role: workstation.macos
      tags: ['workstation']
  