---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname sonarr
  namespace: flux-system
spec:
  targetNamespace: security
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./cluster/apps/security/authentik/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: network
  wait: true
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: dragonfly-cluster
