---
- include_tasks: network.yml
  tags:
    - network

- name: Check if cluster is installed
  ansible.builtin.stat:
    path: "/etc/rancher/k3s/config.yaml"
  register: k3s_check_installed
  check_mode: false

- name: Set manifest facts
  ansible.builtin.set_fact:
    k3s_server_manifests_templates: []
    k3s_server_manifests_urls: []
  when: k3s_check_installed.stat.exists

- name: Install Kubernetes
  ansible.builtin.include_role:
    name: xanmanning.k3s
    public: "true"