---
local:
  hosts:
    workstation:
      ansible_connection: local
workstations:
  hosts:
    rudy:
      ansible_host: rudy.lan
    jocelyn:
      ansible_host: jocelyn.lan
hypervisors:
  hosts:
    gypsy:
      ansible_host: gypsy.lan
routers:
  hosts:
    crow:
      ansible_host: 10.4.20.1
servonet:
  children:
    control_node:
      hosts:
        tom-4:
          ansible_host: 10.4.88.124
        tom-3:
          ansible_host: 10.4.88.123
        tom-0:
          ansible_host: 10.4.88.120
    worker_node:
      hosts:
        tom-1:
          ansible_host: 10.4.88.121
        tom-2:
          ansible_host: 10.4.88.122
        tom-5:
          ansible_host: 10.4.88.125
