---
hypervisors:
  hosts:
    gpc:
      ansible_host: gpc.lan
media:
  hosts:
    cambot:
      ansible_host: cambot.lan
      ansible_user: root
    cambot-2:
      ansible_host: cambot-2.lan
      ansible_user: root
routers:
  hosts:
    crow:
      ansible_host: crow.lan
