---
local:
  hosts:
    workstation:
      ansible_connection: local
workstations:
  hosts:
    rudy:
      ansible_host: rudy.lan
      ansible_connection: local
    jocelyn:
      ansible_host: jocelyn.lan
      ansible_connection: local
hypervisors:
  hosts:
    gypsy:
      ansible_host: gypsy.lan
    gpc:
      ansible_host: gpc.lan
media:
  hosts:
    # cambot:
    #   ansible_host: cambot.lan
    #   ansible_user: root
    cambot-2:
      ansible_host: cambot-2.lan
      ansible_user: root
routers:
  hosts:
    crow:
      ansible_host: 10.4.20.1
