---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 10.3.6
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
      interval: 5m
  values:
    deployment:
      enabled: true
      kind: DaemonSet
      replicas: 2
    
    service:
      enabled: true
      type: LoadBalancer
      spec:
        externalIPs:
         - 10.4.99.123
    
    logs:
      general:
        format: json
        level: DEBUG
      access:
        enabled: true
        format: json
    
    inggressClass:
      enabled: true
      isDefaultClass: true
      fallbackApiVersion: v1

    ingressRoute:
      dashboard:
        enabled: true
    
    globalArguments:
     - "--serverstransport.insecureskipverify=true"
     - "--providers.kubernetesingress.ingressclass=traefik"
    
    additionalArguments:
     - "--providers.kubernetesingress.ingressendpoint.ip=10.4.99.123"

    ports:
      web:
        port: 8000
        expose: true
        exposedPort: 80
      metrics:
        port: 8082
        expose: true
        exposedPort: 8082
