---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
spec:
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
  install:
    crds: CreateReplace
  interval: 30m
  upgrade:
    crds: CreateReplace
  values:
    config:
      envoyGateway:
        extensionsApis:
          enableEnvoyPatchPolicy: true
        provider:
          type: Kubernetes
          kubernetes:
            deploy:
              type: GatewayNamespace
    global:
      imageRegistry: mirror.gcr.io
