---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-nas-backup
provisioner: nfs
parameters:
  archiveOnDelete: "false"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-nas-backup
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-nas-backup
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
  nfs:
    path: /pool/storage-0/data/backup
    server: gpc.lan
