---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: echo-server
  namespace: networking
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: echo
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 2
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/mendhak/http-https-echo
              tag: 39
            env:
              HTTP_PORT: &port 80
    service:
      main:
        controller: main
        ports:
          http:
            port: *port
    route:
      main:
        hostnames:
          - echo.servonet.lan
          - echo.${EXTERNAL_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: networking
        rules:
          - backendRefs:
              - identifier: main
                port: *port
    resources:
      requests:
        cpu: 5m
        memory: 10Mi
      limits:
        memory: 50Mi
