---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.jetstack.io/
      chart: cert-manager
      version: v1.19.3
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    installCRDs: true
    replicaCount: 1
    extraArgs:
      - --enable-gateway-api
      - --acme-http01-solver-nameservers="10.4.1.1:53"
      - --dns01-recursive-nameservers-only
      - --dns01-recursive-nameservers="10.4.1.1:53"
