---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: cert-manager
  values:
    crds:
      enabled: true
    replicaCount: 1
    extraArgs:
      - --enable-gateway-api
      - --acme-http01-solver-nameservers="10.4.1.1:53"
      - --dns01-recursive-nameservers-only
      - --dns01-recursive-nameservers="10.4.1.1:53"
