---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lldap
  namespace: auth-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: pocket-id-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        ENCRYPTION_KEY: "{{ .POCKETID_ENCRYPTION_KEY }}"
        # MAXMIND_LICENSE_KEY: "{{ .MAXMIND_LICENSE_KEY }}"
        # LDAP
        LDAP_BIND_PASSWORD: "{{ .POCKETID_LDAP_BIND_PASSWORD }}"
        LDAP_USER_SEARCH_FILTER: "{{ .POCKETID_LDAP_SEARCH_FILTER }}"
        # Database
        DB_CONNECTION_STRING: |-
          postgres://{{ .POCKETID_POSTGRES_USER }}:{{ .POCKETID_POSTGRES_PASSWORD }}@pocket-id-postgres17-rw.auth-system.svc.servonet.lan/pocket-id
  data:
    - secretKey: POCKETID_ENCRYPTION_KEY
      remoteRef:
        key: POCKETID_ENCRYPTION_KEY
    - secretKey: POCKETID_LDAP_BIND_PASSWORD
      remoteRef:
        key: POCKETID_LDAP_BIND_PASSWORD
    - secretKey: POCKETID_LDAP_SEARCH_FILTER
      remoteRef:
        key: POCKETID_LDAP_SEARCH_FILTER
    - secretKey: POCKETID_POSTGRES_USER
      remoteRef:
        key: POCKET-ID_POSTGRES_USER
    - secretKey: POCKETID_POSTGRES_PASSWORD
      remoteRef:
        key: POCKET-ID_POSTGRES_PASSWORD
