---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: authentik
  values:
    global:
      image:
        repository: ghcr.io/goauthentik/server
        tag: 2025.4.0
      fullnameOverride: authentik
    authentik:
      log_level: debug
      avatars: "initials"
      # email:
      #   host: "smtp-relay.default.svc.cluster.local"
      #   port: 587
      #   use_tls: false
      #   from: "no-reply@servonet.lan"
      secret_key: file://secrets/secret_key
      error_reporting:
        enable: true
        send_pii: false
        environment: "kryptonian"
      outposts:
        container_image_base: ghcr.io/goauthentik/%(type)s:%(version)s
      postgresql:
        host: "postgres17-rw.data-ops.svc.servonet.lan"
        name: "authentik"
        user: file://secrets/pguser
        password: file://secrets/pgpass
      redis:
        host: "dragonfly.data-ops.svc.servonet.lan"

    server:
      replicas: 1
      pdb:
        enabled: false
        minAvailable: 1
        maxUnavailable: 1
      dnsConfig:
        options:
          - name: ndots
            value: "2"

      route:
        main:
          enabled: true
          hostnames: ["auth.servonet.lan"]
          parentRefs:
            - group: gateway.networking.k8s.io
              kind: Gateway
              name: envoy-internal
              namespace: networking
              sectionName: https
            # - group: gateway.networking.k8s.io
            #   kind: Gateway
            #   name: envoy-external
            #   namespace: networking
            #   sectionName: https
      metrics:
        serviceMonitor:
          enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          memory: 2Gi
    worker:
      replicas: 1
      serviceAccount:
        create: true
      pdb:
        enabled: false
        minAvailable: 1
        maxUnavailable: 1
      resources:
        requests:
          cpu: 50m
          memory: 512Mi
        limits:
          memory: 1.5Gi
      volumes:
        - name: secrets
          secret:
            secretName: authentik-secret
      volumeMounts:
        - name: secrets
          mountPath: /secrets
          readonly: true
    prometheus:
      rules:
        enabled: true

    postgresql:
      enabled: false
    redis:
      enabled: false
