kind: Secret
ansible_user: ENC[AES256_GCM,data:gaBvyg==,iv:UwrxT95ex41MvXtygPQseyJin48rdfZ86j3LjzRbl18=,tag:JfsfbRVcrL1Lle9jqp0RRw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:eWAZ193Y+yKHEA2GkfigYF1g,iv:wC1kojiS6Gm5I+W3NFRB3p+AFVye3jv8jUg0AV2qiaM=,tag:PBjlxnCyAJoPcNpuwYjRQA==,type:str]
become: ENC[AES256_GCM,data:TzrwwgQ=,iv:6OUVpKircIhA+ZsHG4yQU7DNeg3SYiZpEu0B0d4W/RI=,tag:ye/SfprYIOnaXxbQgveb9A==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13a30av7z5dzumzzrpc5pqmmyjmqdmamh8jzxsdz2zgschr9k2p8qz6v5uw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOWZIZTIrVWVQUThlaUkx
            bjVVeE1pYjFhQ09uTS9ZQVgxU0ZYVXBocEZBClZLVDQ5YnJPUkh1SUVWR044RU5W
            c2xrd1VhV0xFOXJCK2prNG0wN0QxQ00KLS0tIG9XK2NoczNsY2g3YXZyREtkcU9K
            NDNUTWp3cVZkdm0raW9TKyt0VUI2azQKPh+M58+cYc5lnZ8LgI/xXTgHwTuP+HiL
            MgIMSC7dtJuhhCJelOM+YTMyEP5yB1QaCII5PIM6Gb/1Kro4n5SljQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-28T02:50:26Z"
    mac: ENC[AES256_GCM,data:r1IZpEvxIjIFlwY3/FHEsWD/kA/XLC7+EIkF6GbMiH/1+LYYcp/s+yH0fXFvTTJ8WubJeNf485iFxRP7Rhz605EhG6L/0oLeOWbrnfRuVkKLDhh7aUjf8ROK6nVCBLEFQNz/mZyduT0i8kCfdmhtjHvr5Z2d7ESO2PgmCKm2l4U=,iv:84Xsh6xUNmGGBWBC7M0GJiVza2v4EZsj1YjrscqPt7M=,tag:PzTe96pdR1lDDar1tTCMQA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
