---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: radarr
      version: 16.2.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/radarr
      tag: v4.1.0.6175
    env:
      TZ: "America/Detroit"
      PUID: 1000
      PGID: 1001

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "step-ca"
        hosts:
          - host: "radarr.lan"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "radarr.lan"
            secretName: radarr-cert
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1001
      fsGroup: 1001
    metrics:
      enabled: true
      serviceMonitor:
        interval: 3m
        scrapeTimeout: 1m
      prometheusRule:
        enabled: true
    persistence:
      config:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "gpc"
            path: /pool/storage-0/media/config/radarr
        mountPath: /config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "gpc"
            path: /pool/storage-0/media
        mountPath: /media
    resources:
      requests:
        memory: 250Mi
        cpu: 1
      limits:
        memory: 1500Mi
