---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  TIMEZONE: "America/Detroit"
  BGP_ROUTER_ADDR: "10.4.1.1"
  BGP_ROUTER_ASN: "65551"
  INGRESS_NGINX_ADDRESS: "10.10.100.101"
  K8S_GATEWAY_ADDRESS: "10.10.100.111"
