---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: repositories
  namespace: flux-system
spec:
  interval: 30m
  path: ./cluster/base/repositories
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: network
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: network
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
  dependsOn:
    - name: repositories
