---
machine:
  features:
    kubernetesTalosAPIAccess:
      enabled: true # Enable Talos API access from Kubernetes pods.
      # The list of Talos API roles which can be granted for access from Kubernetes pods.
      allowedRoles:
        - os:reader
      # The list of Kubernetes namespaces Talos API access is available from.
      allowedKubernetesNamespaces:
        - kube-system
  network:
    interfaces:
      - interface: "eth0"
        dhcp: false
        addresses: ["${static_ip_address}/16"]
        vip:
          ip: "${virtual_ip_address}"
cluster:
  clusterName: servonet.lan
  allowSchedulingOnControlPlanes: true
