---
machine:
  features:
    kubePrism:
      enabled: true
      port: 7445
  install:
    disk: ${disk}
    image: ghcr.io/siderolabs/installer:${talos_version}
    extensions:
      - image: ghcr.io/siderolabs/qemu-guest-agent:${qemu_guest_agent_version}
      - image: ghcr.io/siderolabs/intel-ucode:20240312
      # - image: ghcr.io/siderolabs/i915-ucode:f03609df93532c97873a091119fbe9017fb09245de0f17fdcb64d3b0d055e5f2
