---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.17.1
      sourceRef:
        kind: HelmRepository
        name: nvidia-device-plugin
        namespace: flux-system
  values:
    image:
      repository: nvcr.io/nvidia/k8s-device-plugin
      tag: v0.17.2
    runtimeClassName: nvidia
    nodeSelector:
      feature.node.kubernetes.io/custom-nvidia-gpu: "true"
