---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app paperless
  namespace: flux-system
spec:
  targetNamespace: data-ops
  dependsOn:
    - name: external-secrets-manifests
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./cluster/apps/selfhosted/paperless/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: network
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
