---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.1.0/charts/other/app-template/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jellyfin
  namespace: media
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: jellyfin
  values:
    controllers:
      main:
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1001
            fsGroup: 1001
            fsGroupChangePolicy: OnRootMismatch
          # nodeSelector:
          #   nvidia.feature.node.kubernetes.io/gpu: "true"
          # affinity:
          #   nodeAffinity:
          #     requiredDuringSchedulingIgnoredDuringExecution:
          #       nodeSelectorTerms:
          #         - matchExpressions:
          #             - key: nvidia.feature.node.kubernetes.io/gpu
          #               operator: In
          #               values:
          #                 - "true"
        containers:
          main:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.11.6@sha256:25db4eb10143c1c12adb79ed978e31d94fc98dc499fbae2d38b2c935089ced3e
            env:
              TZ: "America/Detroit"
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_FFmpeg__probesize: 50000000
              JELLYFIN_FFmpeg__analyzeduration: 500000000
              # NVIDIA_VISIBLE_DEVICES: all
              # NVIDIA_DRIVER_CAPABILITIES: all
            resources:
              requests:
                memory: 250Mi
                cpu: 20m
                # nvidia.com/gpu: 1
              limits:
                memory: 2500Mi
                # nvidia.com/gpu: 1
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 8096
    route:
      main:
        hostnames: ["jellyfin.servonet.lan"]
        parentRefs:
          - name: envoy-internal
            namespace: networking
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: "ceph-block"
        size: 8Gi
        accessMode: ReadWriteOnce
        retain: true
      movies:
        existingClaim: nas-movies
      tv:
        existingClaim: nas-tv
      cache:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /cache
