---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname sonarr
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./cluster/apps/media/sonarr/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: network
  wait: true
  dependsOn:
    - name: rook-cluster
