---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  chartRef:
    kind: OCIRepository
    name: cilium
  interval: 30m
  values:
    autoDirectNodeRoutes: true
    bpf:
      datapathMode: netkit
      masquerade: true
      preallocateMaps: true
      tproxy: true
    bgpControlPlane:
      enabled: true
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    cluster:
      name: servonet
      id: 1
    cni:
      exclusive: false
    dashboards:
      enabled: true
    endpointRoutes:
      enabled: true
    envoy:
      enabled: false
    externalIPs:
      enabled: true
    gatewayAPI:
      enabled: false
    hubble:
      enabled: false
    ipam:
      mode: "kubernetes"
    ipv4NativeRoutingCIDR: 10.244.0.0/16
    k8sServiceHost: localhost
    k8sServicePort: 7445
    kubeProxyReplacement: true
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    l2announcements:
      enabled: false
    loadBalancer:
      algorithm: maglev
      mode: dsr
      serviceTopology: true
    localRedirectPolicies:
      enabled: true
    operator:
      dashboards:
        enabled: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      rollOutPods: true
    pmtuDiscovery:
      enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true
    rollOutCiliumPods: true
    routingMode: native
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    socketLB:
      enabled: true
      hostNamespaceOnly: true
