autoDirectNodeRoutes: true
bandwidthManager:
  enabled: true
  bbr: true
# bgp:
#   enabled: false
#   announce:
#     loadbalancerIP: true
#     podCIDR: false
bgpControlPlane:
  enabled: true
bpf:
  masquerade: true
  tproxy: true
  # hostLegacyRouting: true

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
cluster:
  name: servonet.lan
  id: 1

cni:
  exclusive: false

containerRuntime:
  integration: containerd

enableCnpStatusUpdates: true
endpointRoutes:
  enabled: true
endpointStatus:
  enabled: true
  status: "policy"
hubble:
  enabled: true
  serviceMonitor:
    enabled: false

  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http

  relay:
    enabled: true
    rollOutPods: true

  ui:
    enabled: true
    ingress:
      enabled: false
    rollOutPods: true

ipam:
  mode: "kubernetes"
ipv4NativeRoutingCIDR: 10.244.0.0/16
k8sServiceHost: localhost
k8sServicePort: 7445
kubeProxyReplacement: strict
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
rollOutCiliumPods: true
localRedirectPolicy: true
l2announcements:
  enabled: true
loadBalancer:
  algorithm: maglev
  mode: dsr

k8sClientRateLimit:
  burst: 10
  qps: 5

# https://docs.cilium.io/en/latest/network/l2-announcements/
# l2announcements:
#   enabled: true
#   leaseDuration: 300s
#   leaseRenewDeadline: 60s
#   leaseRetryPeriod: 10s

ingressController:
  enabled: false
  loadbalancerMode: shared
operator:
  rollOutPods: true
routingMode: native

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
