---
substitutions:
  esp_name: POE Board #Device Name
  esp_hostname: poe-board
  #ip_address: 192.168.1.107
  #ip_gw: 192.168.1.1
  #ip_netmask: 255.255.255.0
  run_time: 5min #can be as long as needed to get data
  sleep_time: 20min # normal sleep time
  night_sleep_time: 6h # 1st sleep time after midnight
  fonts_dir: ./fonts
  images_dir: ./images

esphome:
  name: ${esp_hostname}
  platform: ESP32
  board: esp32dev

logger:
api:
ota:

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0

i2c:
  - sda: 5
    scl: 4
    scan: true

time:
  - platform: ds1307
    update_interval: never
    address: 0x68
  - platform: sntp
    id: sntp_time
    timezone: America/Detroit
    on_time_sync:
      - ds1307.write_time: