substitutions:
  devicename: living-room-switch
  friendly_name: "Living Room"

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: $friendly_name Fallback Hotspot
    password: "BKBxsYz8b2uQ"

captive_portal:

api:

logger:

ota:

text_sensor:
  - platform: version
    name: Sonoff T1 R2 Version

sensor:
  - platform: uptime
    name: $friendly_name Uptime
    update_interval: 60s

binary_sensor:
  - name: "friendly_name Touchpad 1"
    platform: gpio
    pin:
      number: "GPIO0"
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      - switch.toggle: relay_1
  - platform: gpio
    pin:
      number: "GPIO9"
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: relay_2
    name: "friendly_name Touchpad 2"
  - platform: gpio
    pin:
      number: "GPIO10"
      mode: INPUT_PULLUP
      inverted: true
    name: "friendly_name Touchpad 3"
    on_press:
      - switch.toggle: relay_3
    
  - platform: status
    name: "friendly_name Status"

switch:
  - platform: gpio
    name: "friendly_name Relay 1"
    id: relay_1
    pin: GPIO12
  - platform: gpio
    name: "friendly_name Relay 2"
    id: relay_2
    pin: GPIO5
  - platform: gpio
    name: "friendly_name Relay 3"
    id: relay_3
    pin: GPIO4

output:
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: true

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "friendly_name Blue LED"
    output: blue_led