---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname node-feature-discovery
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./cluster/apps/kube-system/node-feature-discovery/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: network
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname node-feature-discovery-rules
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./cluster/apps/kube-system/node-feature-discovery/rules"
  prune: true
  dependsOn:
    - name: node-feature-discovery
  sourceRef:
    kind: GitRepository
    name: network
  wait: true
