---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.1.0/charts/other/app-template/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: sonarr
  values:
    controllers:
      main:
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1001
            fsGroup: 1001
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/sonarr
              tag: 4.0.16.2943@sha256:0a1b8f5cb5b072f7ad8c6ff64a25dc512115d1a114ecf19a58a3b4f870207ddd
            env:
              TZ: "America/Detroit"
              PUID: 1000
              PGID: 1001
              SONARR__INSTANCE_NAME: Sonarr
              SONARR__PORT: &port 8989
            resources:
              requests:
                memory: 250Mi
                cpu: 20m
              limits:
                memory: 1500Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: *port
    route:
      main:
        hostnames:
          - sonarr.servonet.lan
        parentRefs:
          - name: envoy-internal
            namespace: networking
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: "ceph-block"
        size: 1Gi
        accessMode: ReadWriteOnce
        retain: true
      downloads:
        existingClaim: nas-downloads
      tv:
        existingClaim: nas-tv
