---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname ingress-nginx
  namespace: flux-system
spec:
  targetNamespace: networking
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./cluster/apps/networking/ingress-nginx/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: network
  wait: true
  dependson:
    - name: kube-prometheus-stack
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
