---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: external-secrets
  values:
    installCRDs: true
    replicaCount: 3
    leaderElect: true
    bitwarden-sdk-server:
      enabled: true
      podAnnotations:
        secret.reloader.stakater.com/reload: bitwarden, bitwarden-tls-certs
    grafanaDashboard:
      enabled: true
    serviceMonitor:
      enabled: true
      interval: 1m
    backgroundController:
      serviceMonitor:
        enabled: true
        interval: 1m
    cleanupController:
      serviceMonitor:
        enabled: true
        interval: 1m
    reportsController:
      serviceMonitor:
        enabled: true
        interval: 1m
    webhook:
      replicaCount: 2
