---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: trust-manager
      version: v0.20.3
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    replicaCount: 2
    app:
      trust:
        namespace: kube-system
