---
- name: Update grub template
  ansible.builtin.copy:
    src: "files/grub"
    dest: /etc/default/grub
    mode: 0644
    remote_src: false
  notify: Refresh boot

- name: Update kernel modules
  ansible.builtin.copy:
    src: "files/modules"
    dest: /etc/modules
    mode: 0644
    remote_src: false
  notify: Update kernel modules

