---
- name: Install packages
  include_tasks: packages.yaml

- name: Enable IOMMU
  include_tasks: iommu.yaml

- name: Flush Handlers
  meta: flush_handlers

- name: Setup PVE roles
  include_tasks: pve_roles.yaml
  loop: "{{ pve_roles }}"

- name: Setup users
  include_tasks: users.yaml
  loop: "{{ users }}"

- name: download isos
  include_tasks: isos.yaml
