---
- name: Remove PVE Enterprise repository
  ansible.builtin.apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise
    state: absent
    filename: pve-enterprise
    update_cache: false

- name: Remove Ceph Enterprise repository
  ansible.builtin.apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise
    state: absent
    filename: ceph
    update_cache: false

- name: Add PVE Community repository
  ansible.builtin.apt_repository:
    repo: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
    state: present
    filename: pve-no-subscription

- name: Add Ceph Community repository
  ansible.builtin.apt_repository:
    repo: deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription
    state: present
    filename: ceph

- name: Upgrade all system packages
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_upgrade
  retries: 5
  until: apt_upgrade is success

- name: Install common packages
  ansible.builtin.apt:
    name:
      - jq
    install_recommends: true
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_install_common
  retries: 5
  until: apt_install_common is success
