---
- name: "Check role"
  ansible.builtin.shell:
    cmd: "pveum role list --output-format=json | jq '.[] | .roleid ' | grep {{ item.name }} | cat"
  register: role_exists

- name: "Create role"
  ansible.builtin.shell:
    cmd: pveum roleadd {{ item.name }} -privs "{{ item.privs }}"
  when: role_exists == ""

- name: "Update role"
  ansible.builtin.shell:
    cmd: pveum role modify {{ item.name }} -privs "{{ item.privs }}"
  when: role_exists != ""
