---
- name: Create packer user
  ansible.builtin.shell:
    cmd: pveum useradd packer@pve

- name: Set user password
  ansible.builtin.shell:
    cmd: |-
     pveum passwd packer@pve << PW
     password123
     password123
     PW

- name: Create role
  ansible.builtin.shell:
    cmd: pveum roleadd Packer -privs "VM.Config.Disk VM.Config.CPU VM.Config.Memory Datastore.AllocateSpace Sys.Modify VM.Config.Options VM.Allocate VM.Audit VM.Console VM.Config.CDROM VM.Config.Network VM.PowerMgmt VM.Config.HWType VM.Monitor"

- name: Add user to role
  ansible.builtin.shell:
    cmd: pveum aclmod / -user packer@pve -role Packer