---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
resources:
  - helm-release.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-secrets-config
  namespace: flux-system
resources:
  - clustersecretstore.yaml
