---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname cert-manager
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./cluster/apps/kube-system/cert-manager/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: network
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname cert-manager-manifests
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./cluster/apps/kube-system/cert-manager/manifests"
  prune: true
  dependsOn:
    - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: network
  wait: true
