services:
  caddy:
    image: caddy:2.11.4
    restart: unless-stopped
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - default
      - servarr_default
    volumes:
      - /storage/caddy/config:/etc/caddy
      - /storage/caddy/site:/srv
      - /home/tmc/.step/certs/root_ca.crt:/etc/ssl/certs/proxy_ca_root.crt
      - caddy_data:/data
      - caddy_config:/config
  
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2.8.0
    restart: unless-stopped
    container_name: pocket-id
    env_file: stack.env
    ports:
      - 1411:1411
    volumes:
      - "/storage/pocket/data:/app/data"
    # Optional healthcheck
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

volumes:
  caddy_data:
    external: true
  caddy_config:
    external: true

networks:
  default:
    name: ingress_default
  servarr_default:
    external: true
