---
services:
  gatus:
    image: twinproduction/gatus:latest
    container_name: gatus
    restart: unless-stopped
    ports:
      - "8089:8089"
    volumes:
      - /storage/gatus/config:/config
      - /storage/gatus/data:/data
      - /storage/root_ca.crt:/etc/ssl/certs/proxy_ca_root.crt:ro

    environment:
      - GATUS_CONFIG_PATH=/config/config.yaml

networks:
  default:
    name: monitoring_default
