---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controller:
      main:
        type: statefulset
    pod:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1001
        fsGroup: 1001

    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/sabnzbd
          tag: 4.1.0@sha256:91f3cd6b9f1c9988af5447f464b299630706eb7f691dee857eab1487d4bb626e
        env:
          SABNZBD__PORT: &port 8080
          SABNZBD__HOST_WHITELIST_ENTRIES: >-
            sabnzbd,
            sabnzbd.lan
        resources:
          requests:
            cpu: 5m
            memory: "1024M"
          limits:
            memory: "4096M"

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: &host "sabnzbd.lan"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
