---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: grafana
      version: 7.3.8
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 5m
  values:
    replicas: 1
    env:
      GF_DATE_FORMATS_USE_BROWSER_LOCALE: true
    grafana.ini:
      server:
        root_url: "https://grafana.lan"
      paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
      analytics:
        check_for_updates: false
      log:
        mode: console
      grafana_net:
        url: https://grafana.net
      auth.basic:
        disable_login_form: false
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    datasources:
      datasources.yaml:
        apiVersion: 1
        deleteDatasources:
          - name: Loki
            orgId: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: "https://prometheus.lan"
            tlsSkipVerify: true
          - name: Loki
            type: loki
            access: proxy
            url: https://loki.lan
            tlsSkipVerify: true
    dashboards:
      default:
        flux-cluster:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/cluster.json
          datasource: Prometheus
        flux-control-plane:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/control-plane.json
          datasource: Prometheus
        # radarr:
        #   url: https://raw.githubusercontent.com/k8s-at-home/grafana-dashboards/main/radarr.json
        #   datasource: Prometheus
        # sonarr:
        #   url: https://raw.githubusercontent.com/k8s-at-home/grafana-dashboards/main/sonarr.json
        #   datasource: Prometheus
        speedtest:
          gnetId: 13665
          revision: 1
          datasource: Prometheus
        nginx:
          nginx:
            url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/nginx.json
            datasource: Prometheus
          nginx-request-handling-performance:
            url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/request-handling-performance.json
            datasource: Prometheus
    sidecar:
      dashboards:
        enabled: true
        searchNamespaces: ALL
      datasources:
        enabled: true
        searchNamespaces: ALL
    plugins:
      - grafana-worldmap-panel
      - grafana-clock-panel
    serviceMonitor:
      enabled: true
    ingress:
      enabled: true
      pathType: Prefix
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "step"
      hosts:
        - "grafana.lan"
      tls:
        - hosts:
            - "grafana.lan"
          secretName: grafana-cert
    serviceAccount:
      create: true
      autoMount: true
    persistence:
      enabled: false
