---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname nfs-subdir-external-provisioner
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./cluster/apps/kube-system/nfs-subdir-external-provisioner/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: network
  wait: true
