---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: dvb-tuner
spec:
  rules:
    - name: dvb.tuner
      labels:
        feature.node.kubernetes.io/dvb-tuner: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            "class": { op: In, value: ["ff"]}
            vendor: { op: In, value: ["2040"]}
            device: { op: In, value: ["826d"]}
