---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app excalidraw
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 30m
  values:
    controllers:
      excalidraw:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          hostUsers: false
        containers:
          app:
            image:
              repository: mirror.gcr.io/excalidraw/excalidraw
              tag: latest@sha256:20ffa04668e19616bb0c1b3632849e5cd96e0bc7a1336b73d9d072667f2c2854
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: false
            resources:
              requests:
                cpu: 5m
                memory: 10Mi
              limits:
                memory: 50Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 80
    route:
      app:
        hostnames:
          - draw.servonet.lan
        parentRefs:
          - name: envoy-internal
            namespace: networking
