---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: k8s-at-home-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://bjw-s.github.io/helm-charts
  timeout: 3m
