apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami.yaml
  - bjw-s.yaml
  - crunchydata.yaml
  - emqx-charts.yaml
  - external-dns.yaml
  - external-secrets.yaml
  - grafana.yaml
  - influxdata.yaml
  - ingress-nginx.yaml
  - jetstack.yaml
  - k8s-gateway.yaml
  - metrics-server.yaml
  - minio.yaml
  - nfs-subdir-external-provisioner.yaml
  - node-feature-discovery.yaml
  - prometheus-community.yaml
  - rook-ceph.yaml
