apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami-charts.yaml
  - emqx-charts.yaml
  - external-dns-charts.yaml
  - grafana-charts.yaml
  - influxdata-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-gateway.yaml
  - metallb-charts.yaml
  - metrics-server-charts.yaml
  - minio-charts.yaml
  - nfs-subdir-external-provisioner-charts.yaml
  - node-feature-discovery-charts.yaml
  - prometheus-community-charts.yaml
  - rook-ceph-charts.yaml
