---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authelia
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: authelia
  values:
    controllers:
      authelia:
        replicas: 3
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          enableServiceLinks: true
        containers:
          main:
            image:
              repository: ghcr.io/authelia/authelia
              tag: 4.39.0
            resources:
              requests:
                cpu: 1m
                memory: 50Mi
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
    service:
      main:
        controller: *app
        ports:
          http:
            port: &port 9091
    routes:
      main:
        hostnames: ["auth.servonet.lan"]
        parentRefs:
          - name: envoy-external
            namespace: networking
        rules:
          - backendRefs:
              - name: *app
                port: *port
