---
# Chocolatey - Windows package manager

- name: is choc.exe present
  win_stat:
    path: "{{ choco_path }}/choco.exe"
  register: choco_exe

- name: debug choco_exe
  debug:
    var: choco_exe
    verbosity: 2

- name: isntall Chocolatey
  raw: "$env:chocolateyUseWindowsCompression='{{ choco_win_compression }}'; \
  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
  iex ((New-Object System.Net.WebClient).DownloadString('{{ choco_installer }}'))"
  register: choco_install_status
  when:
    - choco_exe.stat.exists is defined
    - not choco_exe.stat.exists

- name: debug choco_install_status
  debug:
    var: choco_install_status
    verbosity: 3

- name: add choco to path
  win_path:
    name: PATH
    elements: '%ALLUSERSPROFILE\chocolatey\bin%'
    scope: machine
    state: present
