---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: home
spec:
  chart:
    spec:
      chart: nzbget
      sourceRef:
        kind: HelmRepository
        name: k8sathome
  interval: 10m0s