---
- name: Detect fusion io storage.fusionio

- name: Detect kernel module
  register: fio_kernel_module

- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - git
      - gcc
      - pve-headers
      - pve-headers-$(uname -r)
      - zip
      - unzip
      - fakeroot
      - build-essential
      - debhelper
      - rsync
      - dkms
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_install_common
  retries: 5
  until: apt_install_common is success

- block:
  - name: Clone driver repo

  - name: 