---
# - name: Detect fusion io storage.fusionio

# - name: Detect kernel module
#   register: fio_kernel_module

- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - git
      - gcc
      - pve-headers
      - pve-headers-{{ ansible_kernel }}
      - zip
      - unzip
      - fakeroot
      - build-essential
      - debhelper
      - rsync
      - dkms
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_install_common
  retries: 5
  until: apt_install_common is success

- block:
    - name: Clone driver repo
      ansible.builtin.git:
        repo: https://github.com/RemixVSL/iomemory-vsl4.git
        dest: /root/iomemory-vsl4

    - name: Make DKMS module
      ansible.builtin.shell:
        cmd: make dkms
        chdir: /root/iomemory-vsl4
#   when: fio_kernel_modul is set
