---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/tuppr.home-operations.com/kubernetesupgrade_v1alpha1.json
apiVersion: tuppr.home-operations.com/v1alpha1
kind: KubernetesUpgrade
metadata:
  name: kubernetes
spec:
  kubernetes:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
    version: v1.34.1
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      expr: |-
        status.phase in ['Cluster in healthy state']
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      expr: |-
        status.phase in ['Ready']
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      expr: |-
        status.ceph.health in ['HEALTH_OK']
