---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/tuppr.home-operations.com/talosupgrade_v1alpha1.json
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
spec:
  talos:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
    version: v1.12.1
  policy:
    rebootMode: powercycle
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      expr: |-
        status.phase in ['Cluster in healthy state']
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      expr: |-
        status.phase in ['Ready']
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      expr: |-
        status.ceph.health in ['HEALTH_OK']
