---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: networking
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: k8s-gateway
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: k8s-gateway
    domain: "servonet.lan"
    dnsChallenge:
      enabled: true
      domain: "servonet.lan"
    ttl: 1
    service:
      type: LoadBalancer
      port: 53
      annotations:
        io.cilium/lb-ipam-ips: "${K8S_GATEWAY_ADDRESS}"
      externalTrafficPolicy: Cluster
    watchedResources: [HTTPRoute, Service]
