---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
  interval: 10m0s
  values:
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - "10.4.99.1-10.4.99.255"

