timezone: America/Detroit
uid: 1000
gid: 1000

persistence:
  enabled: true
  accessModes:
   - ReadWriteMany
  config:
    name: larry-config
    size: 1Gi
  downloads:
    name: larry-downloads
  tv:
    name: larry-tv
  movies:
    name: larry-movies
storageClass:
  name: larry-nfs-client
nfs:
  server: "10.4.20.108"
  path: /stor

home-assistant:
  uid: 1000
  gid: 1000
  timezone: America/Detroit
  persistence:
    enabled: true
    claimName: larry-config
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: hass.lan
        paths:
          - /

jellyfin:
  uid: 1000
  gid: 1000
  timezone: America/Detroit
  persistence:
    enabled: true
    config:
      claimName: larry-config
    tv:
      claimName: larry-tv
    movies:
      claimName: larry-movies
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: jellyfin.lan
        paths:
          - /

nfs-client-provisioner:
  nfs:
    server: "10.4.20.108"
    path: /stor
  storageClass:
    create: true
    name: larry-nfs-client
    archiveOnDelete: false

nzbget:
  uid: 1000
  gid: 1000
  timezone: America/Detroit
  persistence:
    enabled: true
    useExistingClaim: true
    download:
      claimName: larry-downloads
    config:
      claimName: larry-config
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: nzbget.lan
        paths:
          - /

radarr:
  uid: 1000
  gid: 1000
  timezone: America/Detroit
  persistence:
    enabled: true
    useExistingClaim: true
    downloads:
      claimName: larry-downloads
    movies:
      claimName: larry-movies
    config:
      claimName: larry-config
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: radarr.lan
        paths:
          - /

sonarr:
  uid: 1000
  gid: 1000
  timezone: America/Detroit
  persistence:
    enabled: true
    useExistingClaim: true
    downloads:
      claimName: larry-downloads
    tv:
      claimName: larry-tv
    config:
      claimName: larry-config
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: sonarr.lan
        paths:
          - /