---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.1.0/charts/other/app-template/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tvheadend
  namespace: media
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: tvheadend
  values:
    controllers:
      main:
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1001
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 44 # video group
              - 109 # render group
              - 568 # for NFS access
          nodeSelector:
            feature.node.kubernetes.io/dvb-tuner: "true"
        containers:
          main:
            image:
              repository: ghcr.io/tvheadend/tvheadend
              tag: latest@sha256:bd00456aab44c0b645849121ce72ad619804889bf26b3a55227a591dd3834dbe
            env:
              TZ: "America/Detroit"
              PUID: 1000
              PGID: 1001
            resources:
              requests:
                memory: 100Mi
                cpu: 20m
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 9981
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  failureThreshold: 30
                  periodSeconds: 10
    service:
      main:
        controller: main
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.42.103
        ports:
          http:
            port: *port
            appProtocol: http
          htsp:
            port: 9982
            appProtocol: tcp
    route:
      main:
        hostnames:
          - tv.servonet.lan
        parentRefs:
          - name: envoy-internal
            namespace: networking
    persistence:
      config:
        existingClaim: tvheadend
      recordings:
        enabled: true
        type: nfs
        server: nas.lan
        path: /mnt/storage/media/recordings
      dvb:
        enabled: true
        type: hostPath
        hostPath: /dev/dvb
        globalMounts:
          - path: /dev/dvb

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: feature.node.kubernetes.io/dvb-tuner
                operator: Exists
