---
#
# Below vars are for the xanmanning.k3s role
# ...see https://github.com/PyratLabs/ansible-role-k3s
#

# (string) The interface on the host kube-vip should attach to
kubevip_interface: "eth0"
# (string) The ARP address kube-vip broadcasts
kubevip_address: "10.4.88.223"


# (string) Use a specific version of k3s
k3s_release_version: "v1.25.6+k3s1"

# (bool) Install using hard links rather than symbolic links.
k3s_install_hard_links: true

# (bool) Escalate user privileges for all tasks
k3s_become_for_all: true
k3s_become: true

# (bool) Enable debug logging on the k3s service
k3s_debug: false

# (bool) Enable etcd embedded datastore
k3s_etcd_datastore: false

# (bool) Allow the use of unsupported configurations in k3s
k3s_use_unsupported_config: true

# (string) Control Plane registration address
k3s_registration_address: "{{ kubevip_address }}"

# (list) A list of URLs to deploy on the primary control plane. Read notes below.
k3s_server_manifests_urls:
  - url: https://docs.projectcalico.org/archive/v3.22/manifests/tigera-operator.yaml
    filename: tigera-operator.yaml
  # - url: https://docs.projectcalico.org/manifests/calico.yaml
  #   filename: calico.yaml
  - url: https://kube-vip.io/manifests/rbac.yaml
    filename: kube-vip-rbac.yaml

# (list) A flat list of templates to deploy on the primary control plane
# /var/lib/rancher/k3s/server/manifests
k3s_server_manifests_templates:
  - "calico-installation.yaml.j2"
  - "calico-bgpconfiguration.yaml.j2"
  - "calico-bgppeer.yaml.j2"
  - "kube-vip-daemonset.yaml.j2"

calico_external_cidr: "10.80.2.0/24"
# (bool) Specify if a host (or host group) are part of the control plane
k3s_control_node: true

# (dict) k3s settings for all control-plane nodes
k3s_server:
  node-ip: "{{ ansible_host }}"
  tls-san:
    # kube-vip
    - "{{ kubevip_address }}"
  # Disable Docker - this will use the default containerd CRI
  docker: false
  flannel-backend: "none" # This needs to be in quotes
  disable:
    # Disable flannel - replaced with Calico
    - flannel
    # Disable traefik - installed with Flux
    - traefik
    # Disable servicelb - replaced with metallb and install with Flux
    - servicelb
    # Disable metrics-server - installed with Flux
    - metrics-server
  disable-network-policy: true
  disable-cloud-controller: true
  write-kubeconfig-mode: "644"
  # Network CIDR to use for pod IPs
  cluster-cidr: "10.42.0.0/16"
  # Network CIDR to use for service IPs
  service-cidr: "10.43.0.0/16"
  kubelet-arg:
    # Enables the kubelet to gracefully evict pods during a node shutdown
    - "feature-gates=GracefulNodeShutdown=true"
    # Allow k8s services to contain TCP and UDP on the same port
    - "feature-gates=MixedProtocolLBService=true"
  # Required to monitor kube-controller-manager with kube-prometheus-stack
  kube-controller-manager-arg:
    - "bind-address=0.0.0.0"
  # Required to monitor kube-proxy with kube-prometheus-stack
  kube-proxy-arg:
    - "metrics-bind-address=0.0.0.0"
  # Required to monitor kube-scheduler with kube-prometheus-stack
  kube-scheduler-arg:
    - "bind-address=0.0.0.0"
  # Required to monitor etcd with kube-prometheus-stack
  etcd-expose-metrics: true
  # Required for HAProxy health-checks
  kube-apiserver-arg:
    # Allow k8s services to contain TCP and UDP on the same port
    - "feature-gates=MixedProtocolLBService=true"
    - "anonymous-auth=true"
