---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: default
spec: # CiliumBGPPeeringPolicySpec
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/control-plane: "true"
  virtualRouters: # []CiliumBGPVirtualRouter
    - localASN: 64523
      exportPodCIDR: true
      # Announce all services
      serviceSelector:
        matchExpressions:
          - { key: somekey, operator: NotIn, values: ["never-used-value"] }
      neighbors: # []CiliumBGPNeighbor
        - peerAddress: "10.4.1.1/16"
          peerASN: 65551
          eBGPMultihopTTL: 10
          connectRetryTimeSeconds: 120
          holdTimeSeconds: 90
          keepAliveTimeSeconds: 30
          gracefulRestart:
            enabled: true
            restartTimeSeconds: 120
