apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-config
    labels:
        type: config
spec:
  storageClassName: 
  capacity:
    storage: 1Gi
  accessModes:
   - ReadWriteMany
  hostPath:
    path: "/Users/tcosgriff/Source/network/config"