{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.config.name }}
  labels: 
    {{- include "web-services.configLabels" . | nindent 4}}