{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.config.name }}
  labels: 
    {{- include "web-services.configLabels" . | nindent 4}}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  volumeMode: Filesystem
  storageClassName: {{ .Values.storageClass.name }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote}}
  selector:
    matchLabels:
      {{- include "web-services.configLabels" . | nindent 6 }}
{{- end }}