---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
spec:
  interval: 1h
  path: ./cluster/apps/kube-system/metrics-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: network
    namespace: flux-system
  targetNamespace: kube-system
  wait: false
