---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tinyauth
  namespace: auth-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: tinyauth-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID
      remoteRef:
        key: TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID
    - secretKey: TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET
      remoteRef:
        key: TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET
    - secretKey: TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTID
      remoteRef:
        key: TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTID
    - secretKey: TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTSECRET
      remoteRef:
        key: TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTSECRET
