---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tinyauth
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: tinyauth
  values:
    controllers:
      tinyauth:
        annotations:
          reloader.stakater.com/auto: "true"
          secret.reloader.stakater.com/reload: tinyauth-secret
        containers:
          app:
            image:
              repository: ghcr.io/steveiliop56/tinyauth
              tag: v5.0.7-alpha.1@sha256:5127d62debfd72b54ae1088d721469e1472255799ad405cbb14e5c1aca811f54
            env:
              TZ: America/Detroit
              TINYAUTH_APPURL: https://tinyauth.servonet.lan
              TINYAUTH_DISABLEANALYTICS: true
              TINYAUTH_OAUTH_PROVIDERS_POCKETID_NAME: Pocket-ID
              TINYAUTH_OAUTH_PROVIDERS_POCKETID_AUTHURL: https://id.servonet.lan/authorize
              TINYAUTH_OAUTH_PROVIDERS_POCKETID_TOKENURL: https://id.servonet.lan/api/oidc/token
              TINYAUTH_OAUTH_PROVIDERS_POCKETID_USERINFOURL: https://id.servonet.lan/api/oidc/userinfo
              TINYAUTH_OAUTH_PROVIDERS_POCKETID_SCOPES: openid email profile groups
              TINYAUTH_AUTH_SECURECOOKIE: true
              TINYAUTH_AUTH_SESSIONEXPIRY: 604800
              TINYAUTH_RESOURCESDIR: /data/resources
              TINYAUTH_DATABASEPATH: /data/tinyauth.db
              TINYAUTH_SERVER_TRUSTEDPROXIES: 10.42.0.0/16
            envFrom:
              - secretRef:
                  name: tinyauth-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/healthz
                    port: &port 3000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.servonet.lan"
        parentRefs:
          - name: envoy-internal
            namespace: networking
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      tmpfs:
        type: emptyDir
        advancedMounts:
          tinyauth:
            app:
              - path: /data
                subPath: data
