---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: vault-issuer
  namespace: default
spec:
  vault:
    server: http://vault.lan
    path: pki_int/sign/lan-intermediate
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: issuer
        secretRef:
          name: $ISSUER_SECRET_REF
          key: token
