---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ocirepository.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: flux-instance-values
    files:
      - values.yaml=./values.yaml
configurations:
  - kustomizeconfig.yaml
