---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname rook-operator
  namespace: flux-system
spec:
  targetNamespace: rook-ceph
  commonMetadata:
    labels:
      app.kubernetes.io: *appname
  interval: 10m
  path: "./cluster/apps/operators/rook-ceph/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: network
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname rook-cluster
  namespace: flux-system
spec:
  targetNamespace: rook-ceph
  commonMetadata:
    labels:
      app.kubernetes.io: *appname
  interval: 10m
  path: "./cluster/apps/operators/rook-ceph/cluster"
  prune: true
  sourceRef:
    kind: GitRepository
    name: network
  wait: true
  dependsOn:
    - name: rook-operator
